<?xml version="1.0" encoding="utf-8"?><Database Name="HomeCare" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=HomeCare;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HomeCareConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BloodType" Member="BloodTypes">
    <Type Name="BloodType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="BloodType_PatientInfo" Member="PatientInfos" ThisKey="id" OtherKey="bloodTypeId" Type="PatientInfo" />
    </Type>
  </Table>
  <Table Name="dbo.Caretaker" Member="Caretakers">
    <Type Name="Caretaker">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date_of_employemnt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="User_Caretaker" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Visit" Member="Visits">
    <Type Name="Visit">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contact" Member="Contacts">
    <Type Name="Contact">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="lastname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="otherInfo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="jobTitle" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Contact_PatientInfo_Contact" Member="PatientInfo_Contacts" ThisKey="id" OtherKey="contactId" Type="PatientInfo_Contact" />
    </Type>
  </Table>
  <Table Name="dbo.Handicap" Member="Handicaps">
    <Type Name="Handicap">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Handicap_PatientInfo_Handicap" Member="PatientInfo_Handicaps" ThisKey="id" OtherKey="handicapId" Type="PatientInfo_Handicap" />
    </Type>
  </Table>
  <Table Name="dbo.Illness" Member="Illnesses">
    <Type Name="Illness">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Illness_PatientInfo_Illne" Member="PatientInfo_Illnes" ThisKey="id" OtherKey="illnesId" Type="PatientInfo_Illne" />
    </Type>
  </Table>
  <Table Name="dbo.PatientInfo" Member="PatientInfos">
    <Type Name="PatientInfo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bloodTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dislikes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="comments" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="PatientInfo_PatientInfo_Contact" Member="PatientInfo_Contacts" ThisKey="id" OtherKey="patientId" Type="PatientInfo_Contact" />
      <Association Name="PatientInfo_PatientInfo_Handicap" Member="PatientInfo_Handicaps" ThisKey="id" OtherKey="patientId" Type="PatientInfo_Handicap" />
      <Association Name="PatientInfo_PatientInfo_Illne" Member="PatientInfo_Illnes" ThisKey="id" OtherKey="patientID" Type="PatientInfo_Illne" />
      <Association Name="PatientInfo_PatientInfo_PersonalContact" Member="PatientInfo_PersonalContacts" ThisKey="id" OtherKey="patientID" Type="PatientInfo_PersonalContact" />
      <Association Name="PatientInfo_Task_PatientInfo" Member="Task_PatientInfos" ThisKey="id" OtherKey="patient_id" Type="Task_PatientInfo" />
      <Association Name="BloodType_PatientInfo" Member="BloodType" ThisKey="bloodTypeId" OtherKey="id" Type="BloodType" IsForeignKey="true" />
      <Association Name="User_PatientInfo" Member="User" ThisKey="userId" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientInfo_Contact" Member="PatientInfo_Contacts">
    <Type Name="PatientInfo_Contact">
      <Column Name="contactId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="patientId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Contact_PatientInfo_Contact" Member="Contact" ThisKey="contactId" OtherKey="id" Type="Contact" IsForeignKey="true" />
      <Association Name="PatientInfo_PatientInfo_Contact" Member="PatientInfo" ThisKey="patientId" OtherKey="id" Type="PatientInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientInfo_Handicap" Member="PatientInfo_Handicaps">
    <Type Name="PatientInfo_Handicap">
      <Column Name="patientId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="handicapId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Handicap_PatientInfo_Handicap" Member="Handicap" ThisKey="handicapId" OtherKey="id" Type="Handicap" IsForeignKey="true" />
      <Association Name="PatientInfo_PatientInfo_Handicap" Member="PatientInfo" ThisKey="patientId" OtherKey="id" Type="PatientInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientInfo_Illnes" Member="PatientInfo_Illnes">
    <Type Name="PatientInfo_Illne">
      <Column Name="patientID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="illnesId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Illness_PatientInfo_Illne" Member="Illness" ThisKey="illnesId" OtherKey="id" Type="Illness" IsForeignKey="true" />
      <Association Name="PatientInfo_PatientInfo_Illne" Member="PatientInfo" ThisKey="patientID" OtherKey="id" Type="PatientInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientInfo_PersonalContact" Member="PatientInfo_PersonalContacts">
    <Type Name="PatientInfo_PersonalContact">
      <Column Name="personalContact" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="patientID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PatientInfo_PatientInfo_PersonalContact" Member="PatientInfo" ThisKey="patientID" OtherKey="id" Type="PatientInfo" IsForeignKey="true" />
      <Association Name="PersonalContact_PatientInfo_PersonalContact" Member="PersonalContact1" ThisKey="personalContact" OtherKey="id" Type="PersonalContact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalContacts" Member="PersonalContacts">
    <Type Name="PersonalContact">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="relation" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="otherInfo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="PersonalContact_PatientInfo_PersonalContact" Member="PatientInfo_PersonalContacts" ThisKey="id" OtherKey="personalContact" Type="PatientInfo_PersonalContact" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_Role" Member="Role2" ThisKey="id" OtherKey="id" Type="Role" Cardinality="One" />
      <Association Name="Role_User" Member="Users" ThisKey="id" OtherKey="role_id" Type="User" />
      <Association Name="Role_Role" Member="Role1" ThisKey="id" OtherKey="id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Task" Member="Tasks">
    <Type Name="Task">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Task_Task_PatientInfo" Member="Task_PatientInfos" ThisKey="id" OtherKey="task_id" Type="Task_PatientInfo" />
    </Type>
  </Table>
  <Table Name="dbo.Task_PatientInfo" Member="Task_PatientInfos">
    <Type Name="Task_PatientInfo">
      <Column Name="task_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="patient_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PatientInfo_Task_PatientInfo" Member="PatientInfo" ThisKey="patient_id" OtherKey="id" Type="PatientInfo" IsForeignKey="true" />
      <Association Name="Task_Task_PatientInfo" Member="Task" ThisKey="task_id" OtherKey="id" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="lastname" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="username" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="password" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="contactNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Caretaker" Member="Caretakers" ThisKey="id" OtherKey="user_id" Type="Caretaker" />
      <Association Name="User_PatientInfo" Member="PatientInfos" ThisKey="id" OtherKey="userId" Type="PatientInfo" />
      <Association Name="Role_User" Member="Role" ThisKey="role_id" OtherKey="id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>